AllCops:
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Max: 160

AlignParameters:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

ClassLength:
  Enabled: false
