AllCops:
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Max: 160

Layout/ParameterAlignment:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

ClassLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
